# Generated by Django 5.0.6 on 2024-05-29 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_origin', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('nearest_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('official_number', models.CharField(blank=True, max_length=255, null=True)),
                ('helpdesk_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('helpdesk_number', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('files', models.FileField(upload_to='dispute_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_successful', models.BooleanField(default=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.business')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceID', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_at', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_status', models.CharField(choices=[('awaiting', 'Awaiting'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('payment_success', 'Payment Success'), ('is_approved', 'Is Approved'), ('shipping_service', 'Shipping Service')], max_length=255)),
                ('sent_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('experter', 'Experter'), ('importer', 'Importer')], max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.business')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escrow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.business')),
            ],
        ),
    ]
