# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.10
_src_path: gh:algorandfoundation/algokit-python-template
author_email: bartholomew.bassey@st.futminna.edu.ng
author_name: barth007
contract_name: escrow_platform
deployment_language: python
preset_name: production
project_name: Escrow

